# requiring the environment of NodeJS 10
image: node:8

# add 'node_modules' to cache for speeding up builds
cache:
  paths:
    - _book/
    - node_modules/

before_script:
  - npm install gitbook-cli # install gitbook
  - ./node_modules/.bin/gitbook fetch 3.2.3 # fetch final stable version
  - ./node_modules/.bin/gitbook install # add any requested plugins in book.json

# the 'pages' job will deploy and build your site to the 'public' path
pages:
  stage: deploy
  script:
    - gitbook build . public # build to public path
  artifacts:
    paths:
      - public
  only:
    - master # this job will affect only the 'master' branch
